Create provision provider
gomorpheus/morpheus-nutanix-prism-element-plugin pull request #4
Opened 2024-10-02 22:31 UTC by chucktuffli

2024-10-03 20:42 UTC, ddeyoung requested changes

2024-10-03 20:42 UTC, ddeyoung commented on src/main/resources/scribe/nutanix-prism-element-option-types.scribe
These option types weren't being used by Prism Element (it was using a gsp still) so its a bit confusing. These option types should go in the provision provider's `getNodeOptionTypes()` method. See Prism Central for an example: https://github.com/gomorpheus/morpheus-nutanix-prism-plugin/blob/dc4e2bd9b8ff71efb896137771ab66f6547816e3/src/main/groovy/com/morpheusdata/nutanix/prism/plugin/NutanixPrismProvisionProvider.groovy#L174

2024-10-07 18:21 UTC, chucktuffli commented on src/main/resources/scribe/nutanix-prism-element-option-types.scribe
In looking at the [GSP for Prism Element](https://github.com/gomorpheus/morpheus-ui/blob/65581cc30b3d62738d52e3479872b19f6ffd2053/morpheus-ui/grails-app/views/provisioning/instanceTypes/technology/_nutanix.gsp#L35), it has two hidden fields I don't know how to port:
 - `instanceType.backupType`
 - `instanceTypeLayout.description`
 
Thoughts?

2024-10-09 13:36 UTC, ddeyoung commented on src/main/resources/scribe/nutanix-prism-element-option-types.scribe
Set the field context to change how the field name is rendered in the form. See XCP for an example of both fields: https://github.com/gomorpheus/morpheus-xenserver-plugin/blob/0e1dc1232aeba58365f67e3759ff7b2bd574d47a/src/main/groovy/com/morpheusdata/xen/XenserverProvisionProvider.groovy#L206

2024-10-10 12:49 UTC, ddeyoung approved these changes

2024-10-10 12:50 UTC, merged