[#66066] support for create cloud
gomorpheus/morpheus-nutanix-prism-element-plugin pull request #6
Opened 2024-10-07 17:12 UTC by hpe-mcarlin

2024-10-07 17:15 UTC, hpe-mcarlin commented on src/main/groovy/com/morpheusdata/nutanix/prismelement/plugin/NutanixPrismElementImageStoreDatasetProvider.groovy
> +//                        .withFilter('refId', zoneId) // TODO: how do I do this, no params to pull from?
The original was an option source that pulled this from `params`. I'm not sure how to replicate this in a DatasetProvider. Any ideas?

2024-10-09 13:45 UTC, ddeyoung requested changes

2024-10-09 13:45 UTC, ddeyoung commented on src/main/groovy/com/morpheusdata/nutanix/prismelement/plugin/NutanixPrismElementImageStoreDatasetProvider.groovy
> +//                        .withFilter('refId', zoneId) // TODO: how do I do this, no params to pull from?
query.parameters has the equivalent input params. See this example XCP DatasetProvider: https://github.com/gomorpheus/morpheus-xenserver-plugin/blob/main/src/main/groovy/com/morpheusdata/xen/datasets/VirtualImageDatasetProvider.groovy

It prints params directly but also uses the `query.get()` shorthand: https://github.com/gomorpheus/morpheus-plugin-core/blob/85ac4c5c486109ad457303125c3bcd61b20121c2/morpheus-plugin-api/src/main/java/com/morpheusdata/core/data/DataQuery.java#L340

2024-10-09 16:04 UTC, mcarlinhpe commented on src/main/groovy/com/morpheusdata/nutanix/prismelement/plugin/NutanixPrismElementImageStoreDatasetProvider.groovy
> +//                        .withFilter('refId', zoneId) // TODO: how do I do this, no params to pull from?
Ah okay got it, thanks!

2024-10-10 12:41 UTC, ddeyoung approved these changes

2024-10-10 12:41 UTC, merged